### ISSUE TITLE
Only a few blocks are accepted

### ISSUE THREAD

**Issue by rizaltjr** [dusk-network/itn-installer#58]
After I updated to 0.1.7, why are there so few accepted blocks?
![IMG_20240306_214952](https://github.com/dusk-network/itn-installer/assets/79238915/b46ebc2e-4c59-49b0-a666-611f5162849e)
![IMG_20240306_215006](https://github.com/dusk-network/itn-installer/assets/79238915/e7879987-f5c9-4b2e-83e1-e763875c067b)

**Comment by HDauven** [comment]
@rizaltjr the tool you're using is not an official tool from our side. As you can see in the logs you provide, your node was ahead of the global height the tool provides.
