### ISSUE TITLE
Cant start rusk service

### ISSUE THREAD

**Issue by tytttta** [dusk-network/itn-installer#60]
when i use the cmd "service rusk start", it returns "Job for rusk.service failed because the control process exited with error code.
See "systemctl status rusk.service" and "journalctl -xeu rusk.service" for details."

then i use the cmd "journalctl -xe", it returns  the below message, why ？
----------------
Support: http://www.ubuntu.com/support
░░ 
░░ A start job for unit rusk.service has begun execution.
░░ 
░░ The job identifier is 30808.
Mar 11 21:53:43 VM-4-11-ubuntu sshd[393249]: pam_unix(sshd:auth): check pass; user unknown
Mar 11 21:53:43 VM-4-11-ubuntu sshd[393249]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=170.64.195.73
Mar 11 21:53:43 VM-4-11-ubuntu systemd[1]: rusk.service: Control process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ An ExecStartPre= process belonging to unit rusk.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 1.
Mar 11 21:53:43 VM-4-11-ubuntu systemd[1]: rusk.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ The unit rusk.service has entered the 'failed' state with result 'exit-code'.
Mar 11 21:53:43 VM-4-11-ubuntu systemd[1]: Failed to start DUSK Rusk.
░░ Subject: A start job for unit rusk.service has failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ A start job for unit rusk.service has finished with a failure.
░░ 
░░ The job identifier is 30808 and the job result is failed.
Mar 11 21:53:46 VM-4-11-ubuntu sshd[393249]: Failed password for invalid user awsgui from 170.64.195.73 port 52764 ssh2
Mar 11 21:53:48 VM-4-11-ubuntu sshd[393249]: Connection closed by invalid user awsgui 170.64.195.73 port 52764 [preauth]
Mar 11 21:53:49 VM-4-11-ubuntu sshd[393289]: Invalid user tom from 170.64.195.73 port 48060
---------

**Comment by HDauven** [comment]
@tytttta see the log output:
```sh
sshd[393249]: Failed password for invalid user awsgui from 170.64.195.73 port 52764 ssh2
Mar 11 21:53:48 VM-4-11-ubuntu sshd[393249]: Connection closed by invalid user awsgui 170.64.195.73 port 52764 [preauth]
```

You're either running the service under the wrong user or didn't use the right password for the user of your machine.
